import { DocumentFavorite, DocumentObj } from "../../models/DocumentObj";

export function getDocuments(): DocumentObj[] {
  return [
    {
      id: 1,
      name: "Document.pdf",
      type: "PDF",
      createdAt: new Date("2023-10-15"),
      updatedAt: new Date("2023-10-20"),
      version: "Test",
      creator: "User A",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 1, title: "TCC" },
    },
    {
      id: 2,
      name: "Spreadsheet.xlsx",
      type: "Excel",
      createdAt: new Date("2023-09-10"),
      updatedAt: new Date("2023-10-18"),
      version: "2.0",
      creator: "User B",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 1, title: "TCC" },
    },
    {
      id: 3,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User C",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 1, title: "TCC" },
    },
    {
      id: 4,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User D",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 5,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User E",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 6,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User F",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 7,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User G",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 8,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User H",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 9,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User I",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Backend Node Teste" },
    },
  ];
}

export const formatDate = (date: Date) => {
  return date.toLocaleDateString("pt-BR", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

export function getDocumentsFavorites(): DocumentFavorite[] {
  return [
    {
      id: 1,
      favorite: true,
      name: "Requisitos",
      organization: { id: 1, title: "TCC" },
    },
    {
      id: 2,
      favorite: true,
      name: "Contrato de compra",
      organization: { id: 2, title: "Compras" },
    },
    {
      id: 3,
      favorite: false,
      name: "index",
      organization: { id: 3, title: "Não Definido" },
    },
    {
      id: 4,
      favorite: false,
      name: "Livro",
      organization: { id: 4, title: "Não Definido" },
    },
    {
      id: 5,
      favorite: false,
      name: "Nota fornecedor 100",
      organization: { id: 5, title: "Compras" },
    },
    {
      id: 6,
      favorite: false,
      name: "História de usuário",
      organization: { id: 6, title: "TCC" },
    },
  ];
}

export function getDocumentsTrash(): DocumentObj[] {
  return [
    {
      id: 1,
      name: "Document.pdf",
      type: "PDF",
      createdAt: new Date("2023-10-15"),
      updatedAt: new Date("2023-10-20"),
      version: "Test",
      creator: "User A",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 2,
      name: "Spreadsheet.xlsx",
      type: "Excel",
      createdAt: new Date("2023-09-10"),
      updatedAt: new Date("2023-10-18"),
      version: "2.0",
      creator: "User B",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 3,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User C",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 4,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User D",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 5,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User E",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 6,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User F",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 7,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User G",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 8,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User H",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto Front" },
    },
    {
      id: 9,
      name: "Presentation.pptx",
      type: "PowerPoint",
      createdAt: new Date("2023-08-05"),
      updatedAt: new Date("2023-10-15"),
      version: "1.5",
      creator: "User I",
      imagemSrc: "/login/img_fundo_1.png",
      organization: { id: 2, title: "Projeto backend" },
    },
  ];
}