import { DocumentObj } from "../../models/DocumentObj";
import { organizationType } from "../ConstantsTypes";

export function getDocuments(): DocumentObj[] {
  return [
    {
      documentId: 1,
      documentName: "Document.pdf",
      documentType: "PDF",
      documentCreationDate: new Date("2023-10-15"),
      documentLastModifiedDate: new Date("2023-10-20"),
      documentDescription: "Pdf",
      favorite: true,
      version: "Test",
      creator: "User A",
      imagemSrc: "/login/img_fundo_1.png",
      organization: {
        organizationId: 1,
        organizationName: "Projeto Inovação",
        organizationDescription: "Descrição do Projeto Inovação",
        favorite: true,
        organizationType: organizationType.COLLABORATIVE,
        borderColor: undefined,
        icon: undefined,
      },
    },
    {
      documentId: 2,
      documentName: "Spreadsheet.xlsx",
      documentType: "Excel",
      documentCreationDate: new Date("2023-09-10"),
      documentLastModifiedDate: new Date("2023-10-18"),
      documentDescription: "Planilha Excel",
      favorite: false,
      version: "2.0",
      creator: "User B",
      imagemSrc: "/login/img_fundo_1.png",
      organization: {
        organizationId: 1,
        organizationName: "TCC",
        organizationDescription: "Trabalho de Conclusão de Curso",
        favorite: false,
        organizationType: organizationType.COLLABORATIVE,
        borderColor: undefined,
        icon: undefined,
      },
    },
    {
      documentId: 3,
      documentName: "Presentation.pptx",
      documentType: "PowerPoint",
      documentCreationDate: new Date("2023-08-05"),
      documentLastModifiedDate: new Date("2023-10-15"),
      documentDescription: "Apresentação do projeto",
      favorite: false,
      version: "1.5",
      creator: "User C",
      imagemSrc: "/login/img_fundo_1.png",
      organization: {
        organizationId: 1,
        organizationName: "TCC",
        organizationDescription: "Trabalho de Conclusão de Curso",
        favorite: false,
        organizationType: organizationType.COLLABORATIVE,
        borderColor: undefined,
        icon: undefined,
      },
    },
    {
      documentId: 4,
      documentName: "Presentation.pptx",
      documentType: "PowerPoint",
      documentCreationDate: new Date("2023-08-05"),
      documentLastModifiedDate: new Date("2023-10-15"),
      documentDescription: "Apresentação",
      favorite: false,
      version: "1.5",
      creator: "User D",
      imagemSrc: "/login/img_fundo_1.png",
      organization: {
        organizationId: 2,
        organizationName: "Projeto Front",
        organizationDescription: "Projeto de frontend",
        favorite: false,
        organizationType: organizationType.COLLABORATIVE,
        borderColor: undefined,
        icon: undefined,
      },
    },
    {
      documentId: 5,
      documentName: "Presentation.pptx",
      documentType: "PowerPoint",
      documentCreationDate: new Date("2023-08-05"),
      documentLastModifiedDate: new Date("2023-10-15"),
      documentDescription: "Apresentação",
      favorite: false,
      version: "1.5",
      creator: "User E",
      imagemSrc: "/login/img_fundo_1.png",
      organization: {
        organizationId: 2,
        organizationName: "Projeto Front",
        organizationDescription: "Projeto de frontend",
        favorite: false,
        organizationType: organizationType.COLLABORATIVE,
        borderColor: undefined,
        icon: undefined,
      },
    },
    {
      documentId: 6,
      documentName: "Presentation.pptx",
      documentType: "PowerPoint",
      documentCreationDate: new Date("2023-08-05"),
      documentLastModifiedDate: new Date("2023-10-15"),
      documentDescription: "Apresentação",
      favorite: false,
      version: "1.5",
      creator: "User F",
      imagemSrc: "/login/img_fundo_1.png",
      organization: {
        organizationId: 2,
        organizationName: "Projeto Front",
        organizationDescription: "Projeto de frontend",
        favorite: false,
        organizationType: organizationType.COLLABORATIVE,
        borderColor: undefined,
        icon: undefined,
      },
    },
    {
      documentId: 7,
      documentName: "Presentation.pptx",
      documentType: "PowerPoint",
      documentCreationDate: new Date("2023-08-05"),
      documentLastModifiedDate: new Date("2023-10-15"),
      documentDescription: "Apresentação",
      favorite: false,
      version: "1.5",
      creator: "User G",
      imagemSrc: "/login/img_fundo_1.png",
      organization: {
        organizationId: 2,
        organizationName: "Projeto Front",
        organizationDescription: "Projeto de frontend",
        favorite: false,
        organizationType: organizationType.INDIVIDUAL,
        borderColor: undefined,
        icon: undefined,
      },
    },
    {
      documentId: 8,
      documentName: "Presentation.pptx",
      documentType: "PowerPoint",
      documentCreationDate: new Date("2023-08-05"),
      documentLastModifiedDate: new Date("2023-10-15"),
      documentDescription: "Apresentação",
      favorite: false,
      version: "1.5",
      creator: "User H",
      imagemSrc: "/login/img_fundo_1.png",
      organization: {
        organizationId: 2,
        organizationName: "Projeto Front",
        organizationDescription: "Projeto de frontend",
        favorite: false,
        organizationType: organizationType.INDIVIDUAL,
        borderColor: undefined,
        icon: undefined,
      },
    },
    {
      documentId: 9,
      documentName: "Presentation.pptx",
      documentType: "PowerPoint",
      documentCreationDate: new Date("2023-08-05"),
      documentLastModifiedDate: new Date("2023-10-15"),
      documentDescription: "Apresentação",
      favorite: false,
      version: "1.5",
      creator: "User I",
      imagemSrc: "/login/img_fundo_1.png",
      organization: {
        organizationId: 3,
        organizationName: "Projeto Backend Node Teste",
        organizationDescription: "Projeto de backend em Node.js para testes",
        favorite: false,
        organizationType: organizationType.INDIVIDUAL,
        borderColor: undefined,
        icon: undefined,
      },
    },
  ];
}

export const formatDate = (date: Date) => {
  return date.toLocaleDateString("pt-BR", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

export function getDocumentsTrash(): DocumentObj[] {
  //Temporario apenas para testes visuais
  const docs = getDocuments();
  return docs.filter((doc) => doc.documentId < 5);
}
