import { VersionObj } from "@/app/models/VersionObj";
import { getDocuments } from "../Documents/DocumentsServices";

export function getVersions(): VersionObj[] {
  const documents = getDocuments();

  return [
    {
      documentVersionId: 1,
      versionName: "v1.0",
      versionFilePath: "/files/document_v1.pdf",
      createdAt: new Date("2023-10-15"),
      document: documents[0],
      user: {
        userId: 2,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 2,
      versionName: "v1.1",
      versionFilePath: "/files/document_v1.1.pdf",
      createdAt: new Date("2023-10-20"),
      document: documents[0],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 3,
      versionName: "v2.0",
      versionFilePath: "/files/spreadsheet_v2.xlsx",
      createdAt: new Date("2023-11-01"),
      document: documents[1],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 4,
      versionName: "v1.0",
      versionFilePath: "/files/presentation_v1.pptx",
      createdAt: new Date("2023-09-05"),
      document: documents[2],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 5,
      versionName: "v1.0",
      versionFilePath: "/files/document_v1.pdf",
      createdAt: new Date("2023-10-15"),
      document: documents[0],
      user: {
        userId: 2,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 6,
      versionName: "v1.1",
      versionFilePath: "/files/document_v1.1.pdf",
      createdAt: new Date("2023-10-20"),
      document: documents[0],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 7,
      versionName: "v2.0",
      versionFilePath: "/files/spreadsheet_v2.xlsx",
      createdAt: new Date("2023-11-01"),
      document: documents[1],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 8,
      versionName: "v1.0",
      versionFilePath: "/files/presentation_v1.pptx",
      createdAt: new Date("2023-09-05"),
      document: documents[2],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 9,
      versionName: "v1.0",
      versionFilePath: "/files/document_v1.pdf",
      createdAt: new Date("2023-10-15"),
      document: documents[0],
      user: {
        userId: 2,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 10,
      versionName: "v1.1",
      versionFilePath: "/files/document_v1.1.pdf",
      createdAt: new Date("2023-10-20"),
      document: documents[0],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 11,
      versionName: "v2.0",
      versionFilePath: "/files/spreadsheet_v2.xlsx",
      createdAt: new Date("2023-11-01"),
      document: documents[1],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 12,
      versionName: "v1.0",
      versionFilePath: "/files/presentation_v1.pptx",
      createdAt: new Date("2023-09-05"),
      document: documents[2],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 13,
      versionName: "v1.0",
      versionFilePath: "/files/document_v1.pdf",
      createdAt: new Date("2023-10-15"),
      document: documents[0],
      user: {
        userId: 2,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 14,
      versionName: "v1.1",
      versionFilePath: "/files/document_v1.1.pdf",
      createdAt: new Date("2023-10-20"),
      document: documents[0],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 15,
      versionName: "v2.0",
      versionFilePath: "/files/spreadsheet_v2.xlsx",
      createdAt: new Date("2023-11-01"),
      document: documents[1],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 16,
      versionName: "v1.0",
      versionFilePath: "/files/presentation_v1.pptx",
      createdAt: new Date("2023-09-05"),
      document: documents[2],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 17,
      versionName: "v1.0",
      versionFilePath: "/files/document_v1.pdf",
      createdAt: new Date("2023-10-15"),
      document: documents[0],
      user: {
        userId: 2,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 18,
      versionName: "v1.1",
      versionFilePath: "/files/document_v1.1.pdf",
      createdAt: new Date("2023-10-20"),
      document: documents[0],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 19,
      versionName: "v2.0",
      versionFilePath: "/files/spreadsheet_v2.xlsx",
      createdAt: new Date("2023-11-01"),
      document: documents[1],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 20,
      versionName: "v1.0",
      versionFilePath: "/files/presentation_v1.pptx",
      createdAt: new Date("2023-09-05"),
      document: documents[2],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 21,
      versionName: "v1.0",
      versionFilePath: "/files/document_v1.pdf",
      createdAt: new Date("2023-10-15"),
      document: documents[0],
      user: {
        userId: 2,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 22,
      versionName: "v1.1",
      versionFilePath: "/files/document_v1.1.pdf",
      createdAt: new Date("2023-10-20"),
      document: documents[0],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 23,
      versionName: "v2.0",
      versionFilePath: "/files/spreadsheet_v2.xlsx",
      createdAt: new Date("2023-11-01"),
      document: documents[1],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
    {
      documentVersionId: 24,
      versionName: "v1.0",
      versionFilePath: "/files/presentation_v1.pptx",
      createdAt: new Date("2023-09-05"),
      document: documents[2],
      user: {
        userId: 1,
        username: "User B",
        jwtToken: "mock-token-b",
      },
    },
  ];
}
